---
- name: Set desktop background
  block:
    - name: Copy desktop background
      copy:
        src: files/kali-wallpaper.png
        dest: /usr/share/backgrounds/kali/kali-wallpaper-custom.png
        owner: root
        group: root
        mode: 0644
      become: true
      become_method: sudo

    - name: Configure desktop background
      xfconf:
        channel: xfce4-desktop
        property: /backdrop/screen0/monitorrdp0/workspace0/last-image
        value: /usr/share/backgrounds/kali/kali-wallpaper-custom.png
        value_type: string
        state: present

- name: Install JetBrains Nerd Font
  block:
    - name: Copy JetBrains Nerd Font
      copy:
        src: files/JetBrainsMonoNerdFontMono-Medium.ttf
        dest: /usr/share/fonts/truetype/jetbrains/
        owner: root
        group: root
        mode: 0644
    - name: Update font cache
      ansible.builtin.shell: fc-cache -f -v
    - name: Set default terminal font
      lineinfile:
        path: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal.ini"
        regexp: "^fontFamily="
        line: "fontFamily=JetBrainsMono Nerd Font Mono"
        state: present
      become: false
    - name: Set terminal font size
      lineinfile:
        path: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal.ini"
        regexp: "^fontSize="
        line: "fontSize=10"
        state: present
      become: false
      
  become: true
  become_method: sudo