---
- name: Set desktop background
  block:
    - name: Copy desktop background
      copy:
        src: files/kali-wallpaper.png
        dest: /usr/share/backgrounds/kali/kali-wallpaper-custom.png
        owner: root
        group: root
        mode: 0644
      become: true
      become_method: sudo

    - name: Configure desktop background
      xfconf:
        channel: xfce4-desktop
        property: /backdrop/screen0/monitorrdp0/workspace0/last-image
        value: /usr/share/backgrounds/kali/kali-wallpaper-custom.png
        value_type: string
        state: present

- name: Install JetBrains Nerd Font
  block:
    - name: Copy JetBrains Nerd Font
      copy:
        src: files/JetBrainsMonoNerdFontMono-Medium.ttf
        dest: /usr/share/fonts/truetype/jetbrains/JetBrainsMonoNerdFontMono-Medium.ttf
        owner: root
        group: root
        create: true
        mode: 0644
    - name: Update font cache
      ansible.builtin.shell: fc-cache -f -v
  become: true
  become_method: sudo