---
- name: "Install Tmux plugins (remember to do Prefix+I to install plugins once Tmux is running)"
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

- name: "Install packages"
  become: true
  become_method: ansible.builtin.sudo
  apt:
    update_cache: true
    name:
      - vim
      - xclip
      - curl
      - tmux
      - unzip
      - jq
      - python3-dev
      - pipx
      - ntpdate
      - nfs-common
      - gpg
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - python3-venv
      - exiftool
      - neofetch
      - mitmproxy
      - p7zip-full

- ansible.builtin.import_tasks: go-tools.yml
- ansible.builtin.import_tasks: neovim.yml
- ansible.builtin.import_tasks: keybase.yml
- ansible.builtin.import_tasks: 1password.yml
- ansible.builtin.import_tasks: docker.yml
