---
- name: "Copying dotfiles"
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}"
  with_items:
    - ".tmux.conf"

- name: "Install Tmux plugins (remember to do Prefix+I to install plugins once Tmux is running)"
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

- name: "Install packages"
  become: true
  become_method: ansible.builtin.sudo
  apt:
    update_cache: true
    name: "{{ packages }}"

- name: Determine shell config file
  set_fact:
    rc_file: "{% if ansible_env.SHELL=='/bin/bash' %}.bashrc{% else %}.zshrc{% endif %}"

- name: "Update paths and aliases is in {{ rc_file }}"
  blockinfile:
    dest: "{{ ansible_env.HOME }}/{{ rc_file }}"
    block: |
      export PATH=$PATH:{{ ansible_env.HOME }}/.local/bin
      alias vim='nvim'
      alias gl='git pull'
      alias gp='git push'
      alias gs='git status'
      alias gd='git diff'
      alias gc='git commit -m'
      alias gca='git commit -am'
      alias gco='git checkout'
      alias gcb='git checkout -b'
      alias gcm='git checkout main'
      alias gpsup='git push --set-upstream origin $(git branch --show-current)'
      alias gpristine='git reset --hard && git clean --force -dfx'
      xrdp(){xfreerdp /u:"$2" /p:"$3" /v:"$1" +clipboard /w:1920 /h:1200 /kbd:0x00000414 /kbd-lang:0x0414: /cert-ignore}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - common paths and aliases"
    insertbefore: EOF

- name: "Reload {{ rc_file }}"
  ansible.builtin.shell:
    cmd: "source {{ ansible_env.HOME }}/{{ rc_file }}"
    executable: "{{ ansible_env.SHELL }}"
  when: ansible_check_mode|bool == false

- ansible.builtin.import_tasks: neovim.yml
- ansible.builtin.import_tasks: keybase.yml
- ansible.builtin.import_tasks: 1password.yml
- ansible.builtin.import_tasks: docker.yml
- ansible.builtin.import_tasks: go-tools.yml
- name: Desktop customization (Kali)
  ansible.builtin.import_tasks: customize-kali.yml
  when: ansible_distribution == "Kali"
- name: Desktop customization (Parrot)
  ansible.builtin.import_tasks: customize-parrot.yml
  when: ansible_distribution == "Parrot"
