---
# vars file for workstation
packages:
  - vim
  - xclip
  - curl
  - tmux
  - unzip
  - jq
  - python3-dev
  - pipx
  - ntpdate
  - nfs-common
  - gpg
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - python3-pip
  - python3-venv
  - exiftool
  - neofetch
  - p7zip-full