- name: "Check if BurpSuiteCA.der exists"
  stat:
    path: /usr/local/share/ca-certificates/BurpSuiteCA.der
  register: burp_cert
  
- name: "Copying Burp Script"
  copy:
    src: files/getburpcert.sh
    dest: /tmp/getburpcert.sh
    mode: 0744
  when: burp_cert.stat.exists == False

- name: "Executing bash script to Download CA Certificate"
  shell:
    /tmp/getburpcert.sh
  when: burp_cert.stat.exists == False

- name: "Copying CA Certificate to /usr/local/share/ca-certificates"
  copy:
    src: /tmp/cacert.der
    dest: /usr/local/share/ca-certificates/BurpSuiteCA.der
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  when: burp_cert.stat.exists == False

- name: Create directory for Burp Suite extras
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

- name: Download jar files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
    checksum: "{{ item.value.checksum }}"
    mode: '0644'
  become: true
  become_method: sudo
  loop: "{{ lookup('dict', burpsuite_extras_jars) }}"
  
- name: Copy BurpSuite Community Config
  template:
    src: "templates/UserConfigCommunity.json.j2"
    dest: "/home/{{ ansible_user_id }}/.BurpSuite/UserConfigCommunity.json"

- name: Install Burp Professional
  block:
  - name: Download Burp Suite Pro
    ansible.builtin.get_url:
      url: https://portswigger-cdn.net/burp/releases/download?product=pro&version=2023.10.1.1&type=Linux
      dest: /tmp/burpsuite_pro.sh
      checksum: "af706e34a1730c4849bada1b81d392ada64ae2d94cdc9ea336d938d6ce2087e9"
      mode: '0744'
  - name: Install Burp Suite Pro
    shell: /tmp/burpsuite_pro.sh -q -dir /opt/burpsuite_pro
    args:
      creates: /opt/burpsuite_pro
  - name: Cleanup
    file:
      path: /tmp/burpsuite_pro.sh
      state: absent
  become: true
  become_method: sudo

