---
- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection", location: "/opt/SharpCollection" }
    - { repo: "https://github.com/AlmondOffSec/PassTheCert", location: "/opt/PassTheCert" }
    - { repo: "https://github.com/tarunkant/Gopherus", location: "/opt/Gopherus" }
    - { repo: "https://github.com/4ndr34z/shells", location: "/opt/shells" }
    - { repo: "https://github.com/arget13/DDexec", location: "/opt/ddexec" }    
    - { repo: "https://github.com/danielbohannon/Invoke-Obfuscation", location: "/opt/Invoke-Obfuscation"}
    - { repo: "https://github.com/mandatoryprogrammer/xsshunter-express", location: "/opt/xsshunter" }
    - { repo: "https://github.com/Kevin-Robertson/Inveigh", location: "/opt/Inveigh" }
  become: true
  ignore_errors: true
  become_method: sudo

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying python script to download github releases"
  copy:
    src: "files/githubdownload.py"
    dest: "{{ build_dir.path }}/githubdownload.py"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Downloading github releases"
  shell: "{{ build_dir.path }}/githubdownload.py {{ item.repo }} {{ item.regex }} {{ item.location }} {% if item.filename is defined %}{{ item.filename }}{% endif %}"
  loop:
    - { repo: "jpillora/chisel",  regex: "_linux_amd64.gz", location: "/opt/chisel" }
    - { repo: "jpillora/chisel",  regex: "_windows_amd64.gz", location: "/opt/chisel" }
    #- { repo: "jpillora/chisel",  regex: "_darwin_amd64", location: "/opt/chisel", filename: "chisel_osx" }
    - { repo: "carlospolop/PEASS-ng",  regex: "linpeas.sh", location: "/opt/peas" }
    - { repo: "carlospolop/PEASS-ng",  regex: "winPEASx64.exe", location: "/opt/peas" }
    - { repo: "WithSecureLabs/chainsaw",  regex: "chainsaw_all_", location: "/opt/" }
    - { repo: "BloodHoundAD/BloodHound", regex: "BloodHound-linux-x64.zip", location: "/opt/" }
    - { repo: "DominicBreuker/pspy", regex: "pspy64", location: "/opt/pspy" }
    - { repo: "DominicBreuker/pspy", regex: "pspy32", location: "/opt/pspy" }
    - { repo: "vinsworldcom/NetCat64", regex: "nc64.exe", location: "/opt/nc64" }
    - { repo: "vinsworldcom/NetCat64", regex: "nc64-32.exe", location: "/opt/nc64" }
    - { repo: "trufflesecurity/trufflehog", regex: "_linux_amd64.tar.gz", location: "/opt/trufflehog" }
  async: 45
  poll: 0
  become: true
  ignore_errors: true
  become_method: sudo

- name: Remove temporary build directory
  ansible.builtin.file:
    path: "{{ build_dir.path }}"
    state: absent
  when: build_dir.path is defined
