---
# tasks file for penetration-testing
- name: Load distribution configuration
  include_vars: 
    file: "../vars/{{ ansible_distribution|lower }}.yml" 

- name: Install common packages
  become: true
  become_method: ansible.builtin.sudo
  apt:
    update_cache: true
    name: "{{ pentest_packages }}"

- name: Install distro-specific packages
  become: true
  become_method: ansible.builtin.sudo
  apt:
    update_cache: true
    name: "{{ extra_packages }}"

- ansible.builtin.import_tasks: "burp.yml"
- ansible.builtin.import_tasks: "firefox.yml"
- ansible.builtin.import_tasks: "go-tools.yml"
- ansible.builtin.import_tasks: "python-tools.yml"
- ansible.builtin.import_tasks: "gem-tools.yml"
- ansible.builtin.import_tasks: "github-repos.yml"
- ansible.builtin.import_tasks: "kerbrute.yml"
