---
# tasks file for penetration-testing
- name: Install Kali-specific packages
  import_tasks: kali.yml
  when: ansible_facts['os_family']|lower == 'kali'

- name: Install Parrot-specific packages
  import_tasks: parrot.yml
  when: ansible_facts['os_family']|lower == 'parrot'