---
# tasks file for penetration-testing
- name: Install Kali-specific packages
  import_tasks: kali.yml
  when: ansible_facts['os_family']|lower == 'kali'

- name: Install Parrot-specific packages
  import_tasks: parrot.yml
  when: ansible_facts['os_family']|lower == 'parrot'

- ansible.builtin.import_tasks: "burp.yml"
- ansible.builtin.import_tasks: "firefox.yml"
- ansible.builtin.import_tasks: "go-tools.yml"
- ansible.builtin.import_tasks: "python-tools.yml"
- ansible.builtin.import_tasks: "gem-tools.yml"
- ansible.builtin.import_tasks: "github-repos.yml"
- ansible.builtin.import_tasks: "kerbrute.yml"