---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url | default('') }}"
    state: latest
  loop:
    - { name: "impacket", url: "git+https://github.com/fortra/impacket.git" }
    - {
        name: "crackmapexec",
        url: "git+https://github.com/Porchetta-Industries/CrackMapExec.git",
      }
    - { name: "certipy-ad", url: "git+https://github.com/ly4k/Certipy.git" }
    - {
        name: "autorecon",
        url: "git+https://github.com/Tib3rius/AutoRecon.git",
      }
    - { name: "ssh-mitm", url: "git+https://github.com/ssh-mitm/ssh-mitm.git" }

- name: "Install pip tools"
  pip:
    name:
      - "pycryptodome"
      - "name-that-hash"
      - "ludvig"
      - "git-dumper"
      - "frida-tools"
      - "xsstrike"
    state: latest
  become: true
  become_method: sudo
