---
# tasks file for dev
- ansible.builtin.import_tasks: golang.yml
- name: Install pre-requisites (Kali)
  ansible.builtin.import_tasks: prereq-kali.yml
  when: ansible_distribution == "Kali"
- ansible.builtin.import_tasks: dotnet.yml
- ansible.builtin.import_tasks: github-client.yml
- ansible.builtin.import_tasks: github.yml
- ansible.builtin.import_tasks: nodejs.yml

