---
- name: "Import Nodesource GPG key"
  shell:
    cmd: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    creates: /etc/apt/keyrings/nodesource.gpg
  become: true
  become_method: sudo

- name: "Create repository file for NodeJS"
  shell:
    cmd: echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    creates: /etc/apt/sources.list.d/nodesource.list
  become: true
  become_method: sudo

- name: "Install NodeJS"
  apt:
    name:
      - nodejs
    state: present
    update_cache: yes
  become: true
  become_method: sudo
