---
- name: "Installing nodejs_20.x repository"
  shell:
    cmd: curl -sL https://deb.nodesource.com/setup_20.x | bash
    creates: /usr/bin/npm
  become: true
  become_method: sudo

- name: "Install NodeJS"
  apt:
    name:
      - nodejs
    state: present
  become: true
  become_method: sudo
