---
- name: "Install Microsoft package repository"
  shell:
    cmd: |
      wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      dpkg -i packages-microsoft-prod.deb
      rm packages-microsoft-prod.deb
    chdir: /tmp
    creates: /etc/apt/sources.list.d/microsoft-prod.list
  become: true
  become_method: sudo  